name: Test Pycorrector

on:
  push:
    branches:
      - feature/spell-inspect
  workflow_dispatch:

jobs:
  build-pycorrector-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      
      - name: Install dependencies
        run: |
          pip install notion-client
          pip install pangu
          pip install python-slugify
          pip install requests
          pip install pycorrector
          pip install https://github.com/kpu/kenlm/archive/master.zip
      
      - name: Run pycorrector tests
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_TOKEN_BLOG_URL: ${{ secrets.NOTION_TOKEN_BLOG_URL }}
        run: |
          python -m unittest tests.corrects_test.CorrectsApiTest.test_pycorrector_spelling_inspect_writer_r2
      
      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: spell-inspect-results
          path: ./build/SpellInspect
